### ISSUE TITLE
How to setup GraphQL Transport ?

### ISSUE THREAD

**Issue by Aetherall** [js-accounts/graphql#18]
Hi!

I want to use this package within a SSR app, so I need to authenticate my user on first request, but  also into my graphQL API

Can you explain me quickly how to do so ?

Should I use rest-client and store tokens in the cookies, and then use the express-rest middleware to log the user before reaching the ggraphql middleware ?

Or should I use the graphQL transport ? How this transport proceed ?

Maybe both, I'm confused

Thanks !

@davidyaha ?

**Comment by coleturner** [comment]
Found this, in case anyone is still looking:

https://github.com/accounts-js/graphql/tree/master/packages/graphql-api

**Comment by Aetherall** [comment]
A new documentation website will be available soon !
